export { ProductRouter } from './products/index.js'
export { CartRouter } from './cart/index.js'
export { AuthRouter } from './auth/index.js'
export { InfoRouter } from './info/index.js'
export { RandomRouter } from './randoms/index.js'